import type { RuleDecision } from "../types.js";

export interface ClaudeMdConfig {
  decisions: RuleDecision[];
  projectName?: string;
}

/**
 * Generate CLAUDE.md content from rule decisions.
 * CLAUDE.md is the "soft constraint" medium — loaded every session.
 */
export function generateClaudeMd(config: ClaudeMdConfig): string {
  const { decisions, projectName } = config;

  const lines: string[] = [];
  lines.push(`# ${projectName || "Project"} — Harness Rules`);
  lines.push("");
  lines.push("<!-- Auto-generated by Harness Automation System -->");
  lines.push("");

  // Design §8.1: CLAUDE.md includes claude_md and linter_warn rules only.
  // claude_md: cognitive guidance (both formal and non-formalizable rules that need LLM awareness)
  // linter_warn: soft constraints (should explain when it's OK to ignore)
  const claudeMdRules = decisions.filter(
    (d) => d.recommendedMedium === "claude_md" || d.recommendedMedium === "claude.md",
  );
  const softRules = decisions.filter(
    (d) => d.recommendedMedium === "linter_warn" || d.recommendedMedium === "linter",
  );
  const inClaudeMd = new Set([
    ...claudeMdRules.map((d) => d.ruleId),
    ...softRules.map((d) => d.ruleId),
  ]);
  const referenceRules = decisions.filter(
    (d) => !inClaudeMd.has(d.ruleId),
  );

  // Cognitive subsection (rules needing cognitive support inside claude_md)
  const cognitiveRules = claudeMdRules.filter((d) => d.cognitiveLayerRequired);
  const guidelineRules = claudeMdRules.filter((d) => !d.cognitiveLayerRequired);

  if (cognitiveRules.length > 0) {
    lines.push("## 认知层规则 (Cognitive Rules)");
    lines.push("");
    lines.push("以下规则需要您在开发过程中主动判断和遵守：");
    lines.push("");
    for (const rule of cognitiveRules) {
      lines.push(`### ${rule.ruleName}`);
      lines.push(`- **规则**: ${rule.reasons[0] || ""}`);
      for (const trigger of rule.cognitiveSkillTriggers) {
        lines.push(`- **认知层辅助**: 触发 "${trigger}" Skill`);
      }
      lines.push("");
    }
  }

  if (guidelineRules.length > 0) {
    lines.push("## 指引规则 (Guidelines)");
    lines.push("");
    lines.push("以下规则为开发指引，建议在开发过程中参考：");
    lines.push("");
    for (const rule of guidelineRules) {
      lines.push(`- **${rule.ruleName}**: ${rule.reasons.join("; ")}`);
    }
    lines.push("");
  }

  if (softRules.length > 0) {
    lines.push("## 软约束规则 (Soft Constraints)");
    lines.push("");
    lines.push("以下规则通过 linter 警告提醒，您在理解背景后可酌情跳过：");
    lines.push("");
    for (const rule of softRules) {
      lines.push(`- **${rule.ruleName}**: ${rule.reasons.join("; ")}`);
    }
    lines.push("");
  }

  if (referenceRules.length > 0) {
    lines.push("## 参考规则 (Reference)");
    lines.push("");
    lines.push("以下规则已通过其他介质自动执行：");
    lines.push("");
    for (const rule of referenceRules) {
      lines.push(
        `- **${rule.ruleName}** → 由 \`${rule.recommendedMedium}\` 自动执行`,
      );
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by Harness Automation System v1.0*");

  return lines.join("\n");
}
