import type { RuleDecision } from "../types.js";

export interface ClaudeMdConfig {
  decisions: RuleDecision[];
  projectName?: string;
}

/**
 * Generate CLAUDE.md content from rule decisions.
 * CLAUDE.md is the "soft constraint" medium — loaded every session.
 */
export function generateClaudeMd(config: ClaudeMdConfig): string {
  const { decisions, projectName } = config;

  const lines: string[] = [];
  lines.push(`# ${projectName || "Project"} — Harness Rules`);
  lines.push("");
  lines.push("<!-- Auto-generated by Harness Automation System -->");
  lines.push("");

  // Cognitive rules first (non-formalizable, need LLM awareness)
  const cognitiveRules = decisions.filter((d) => d.cognitiveLayerRequired);
  const formalRules = decisions.filter(
    (d) => d.recommendedMedium === "claude.md" && !d.cognitiveLayerRequired,
  );
  const referenceRules = decisions.filter(
    (d) => d.recommendedMedium !== "claude.md" && !d.cognitiveLayerRequired,
  );

  if (cognitiveRules.length > 0) {
    lines.push("## 认知层规则 (Cognitive Rules)");
    lines.push("");
    lines.push("以下规则需要您在开发过程中主动判断和遵守：");
    lines.push("");
    for (const rule of cognitiveRules) {
      lines.push(`### ${rule.ruleName}`);
      lines.push(`- **规则**: ${rule.reasons[0] || ""}`);
      for (const trigger of rule.cognitiveSkillTriggers) {
        lines.push(`- **认知层辅助**: 触发 "${trigger}" Skill`);
      }
      lines.push("");
    }
  }

  if (formalRules.length > 0) {
    lines.push("## 软约束规则 (Soft Constraints)");
    lines.push("");
    for (const rule of formalRules) {
      lines.push(`- **${rule.ruleName}**: ${rule.reasons.join("; ")}`);
    }
    lines.push("");
  }

  if (referenceRules.length > 0) {
    lines.push("## 参考规则 (Reference)");
    lines.push("");
    lines.push("以下规则已通过其他介质自动执行：");
    lines.push("");
    for (const rule of referenceRules) {
      lines.push(
        `- **${rule.ruleName}** → 由 \`${rule.recommendedMedium}\` 自动执行`,
      );
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by Harness Automation System v1.0*");

  return lines.join("\n");
}
