import { describe, it, expect } from "vitest";
import { generateClaudeMd } from "./claude_md.js";
import type { RuleDecision } from "../types.js";

function cognitiveRule(overrides?: Partial<RuleDecision>): RuleDecision {
  return {
    ruleId: "R003",
    ruleName: "prefer-early-return",
    recommendedMedium: "claude_md",
    alternativeMedia: [],
    confidence: 0.7,
    reasons: ["Use early returns to reduce nesting"],
    cognitiveLayerRequired: true,
    cognitiveSkillTriggers: ["diagnostic", "educational"],
    ...overrides,
  };
}

function softRule(overrides?: Partial<RuleDecision>): RuleDecision {
  return {
    ruleId: "R013",
    ruleName: "code-review-required",
    recommendedMedium: "claude_md",
    alternativeMedia: [],
    confidence: 0.8,
    reasons: ["All important changes must be reviewed"],
    cognitiveLayerRequired: false,
    cognitiveSkillTriggers: [],
    ...overrides,
  };
}

function refRule(overrides?: Partial<RuleDecision>): RuleDecision {
  return {
    ruleId: "R001",
    ruleName: "no-console-log",
    recommendedMedium: "linter_warn",
    alternativeMedia: [],
    confidence: 0.85,
    reasons: ["Use logger instead"],
    cognitiveLayerRequired: false,
    cognitiveSkillTriggers: [],
    ...overrides,
  };
}

function taskBoardRule(): RuleDecision {
  return {
    ruleId: "R017",
    ruleName: "task-board",
    recommendedMedium: "claude_md",
    alternativeMedia: ["settings", "hook"],
    confidence: 0.85,
    reasons: ["统一的任务看板格式确保团队一致性"],
    cognitiveLayerRequired: false,
    cognitiveSkillTriggers: [],
  };
}

function changelogRule(): RuleDecision {
  return {
    ruleId: "R018",
    ruleName: "changelog-convention",
    recommendedMedium: "claude_md",
    alternativeMedia: ["settings", "hook"],
    confidence: 0.85,
    reasons: ["结构化的变更日志便于程序化分析"],
    cognitiveLayerRequired: false,
    cognitiveSkillTriggers: [],
  };
}

describe("generateClaudeMd", () => {
  // 1. 空 decisions
  it("produces output with no rule blocks for empty decisions", () => {
    const result = generateClaudeMd({ decisions: [] });
    expect(result.length).toBeGreaterThan(0);
    expect(result).not.toContain("###");
    // Prose mentions are OK; actual rule section headers should not appear
    expect(result).not.toContain("## 认知层规则");
    expect(result).not.toContain("## 软约束规则");
    expect(result).not.toContain("## 参考规则");
    // Harness overview section is always present
    expect(result).toContain("## Harness 约束体系");
  });

  // 2. 仅 cognitive rules
  it("includes cognitive section for cognitive-only decisions", () => {
    const result = generateClaudeMd({ decisions: [cognitiveRule()] });
    expect(result).toContain("## 认知层规则 (Cognitive Rules)");
    expect(result).toContain("prefer-early-return");
    expect(result).toContain("diagnostic");
    expect(result).toContain("educational");
  });

  // 3. 仅指引规则
  it("includes guidelines section for claude_md non-cognitive decisions", () => {
    const decisions = [
      softRule(),
      softRule({ ruleId: "R009", ruleName: "no-duplicate-code", reasons: ["Extract common logic"] }),
    ];
    const result = generateClaudeMd({ decisions });
    expect(result).toContain("## 指引规则 (Guidelines)");
    expect(result).toContain("code-review-required");
    expect(result).toContain("no-duplicate-code");
  });

  // 4. 混合类型
  it("includes all sections for mixed decision types", () => {
    // refRule with "hook" medium → goes to reference section
    const ref = refRule({ recommendedMedium: "hook" });
    const decisions = [cognitiveRule(), softRule(), ref];
    const result = generateClaudeMd({ decisions });
    expect(result).toContain("认知层规则");
    expect(result).toContain("指引规则 (Guidelines)");
    expect(result).toContain("参考规则 (Reference)");
    expect(result).toContain("→ 由 `hook` 自动执行");
  });

  // 5. projectName 参数
  it("uses projectName in the title", () => {
    const result = generateClaudeMd({ decisions: [], projectName: "MyApp" });
    expect(result.startsWith("# MyApp — Harness Rules")).toBe(true);
  });

  // 内容结构断言
  it("includes auto-generated mark and version footer", () => {
    const result = generateClaudeMd({ decisions: [cognitiveRule()] });
    expect(result).toContain("Auto-generated by Harness Automation System");
    expect(result).toContain("Generated by Harness Automation System v1.0");
  });

  // Hard constraints tests
  it("includes hard constraints section when R017 is present", () => {
    const result = generateClaudeMd({ decisions: [taskBoardRule(), cognitiveRule()] });
    expect(result).toContain("## 硬约束 (Hard Constraints)");
    expect(result).toContain("任务看板管理");
    expect(result).toContain("scripts/task.py");
    expect(result).toContain("TASK.json");
    expect(result).toContain("**禁止**");
  });

  it("includes hard constraints section when R018 is present", () => {
    const result = generateClaudeMd({ decisions: [changelogRule()] });
    expect(result).toContain("变更日志管理");
    expect(result).toContain("scripts/changelog.py");
  });

  it("includes both hard constraints when both R017 and R018 are present", () => {
    const result = generateClaudeMd({ decisions: [taskBoardRule(), changelogRule()] });
    expect(result).toContain("任务看板管理");
    expect(result).toContain("变更日志管理");
    expect(result).toContain("scripts/task.py");
    expect(result).toContain("scripts/changelog.py");
  });

  it("does not duplicate hard constraints in cognitive or guideline sections", () => {
    const result = generateClaudeMd({ decisions: [taskBoardRule(), cognitiveRule()] });
    const hardConstraintIndex = result.indexOf("## 硬约束");
    const cognitiveIndex = result.indexOf("## 认知层规则");
    const guidelineIndex = result.indexOf("## 指引规则");

    // Hard constraints section should appear before cognitive/guideline
    if (cognitiveIndex > -1) expect(hardConstraintIndex).toBeLessThan(cognitiveIndex);
    if (guidelineIndex > -1) expect(hardConstraintIndex).toBeLessThan(guidelineIndex);

    // task-board should NOT appear in cognitive section
    const afterHardConstraint = result.slice(hardConstraintIndex + 50);
    // Count occurrences of "task-board" — should be exactly 1 (in hard constraints only)
    const taskBoardMatches = result.match(/task-board/g);
    expect(taskBoardMatches?.length).toBe(1);
  });

  // Team Collaboration tests
  it("omits Team Collaboration section when collaborationMode is solo", () => {
    const result = generateClaudeMd({
      decisions: [cognitiveRule()],
      collaborationMode: "solo",
    });
    expect(result).not.toContain("## Team Collaboration");
    expect(result).not.toContain("Git 工作流");
    expect(result).not.toContain("Code Review");
    expect(result).not.toContain("AI 参与度记录");
    expect(result).not.toContain("新成员 Onboarding");
  });

  it("generates Team Collaboration section when collaborationMode is team", () => {
    const result = generateClaudeMd({
      decisions: [cognitiveRule()],
      collaborationMode: "team",
    });
    expect(result).toContain("## Team Collaboration");
    expect(result).toContain("Git 工作流");
    expect(result).toContain("feature/<描述>, bugfix/<描述>, hotfix/<描述>, release/<版本>");
    expect(result).toContain("从 main 分支创建功能分支，完成后通过 Merge Request 合并");
    expect(result).toContain("### Code Review");
    expect(result).toContain("所有 MR 需要至少 1 人 Approve");
    expect(result).toContain("AI Code Review 在 CI 中自动运行，审查结果作为参考");
    expect(result).toContain("Review 关注：逻辑正确性、安全性、性能、可维护性");
    expect(result).toContain("### AI 参与度记录");
    expect(result).toContain("在 MR 描述中标注 AI 工具使用情况");
    expect(result).toContain("Co-Authored-By");
    expect(result).toContain("### 新成员 Onboarding");
    expect(result).toContain("bash scripts/onboard.sh");
    expect(result).toContain(".gitlab/merge_request_templates/default.md");
    // Should NOT include dual-remote note when gitProvider is not "both"
    expect(result).not.toContain("双远程");
  });

  it("includes dual-remote note when collaborationMode is team and gitProvider is both", () => {
    const result = generateClaudeMd({
      decisions: [cognitiveRule()],
      collaborationMode: "team",
      gitProvider: "both",
    });
    expect(result).toContain("## Team Collaboration");
    expect(result).toContain("双远程：GitLab（团队主仓库）+ GitHub（个人备份）");
  });

  it("includes CLI usage in hard constraints section", () => {
    const result = generateClaudeMd({ decisions: [taskBoardRule(), changelogRule()] });
    expect(result).toContain("python3 scripts/task.py list");
    expect(result).toContain("python3 scripts/task.py show");
    expect(result).toContain("python3 scripts/task.py update");
    expect(result).toContain("python3 scripts/task.py summary");
    expect(result).toContain("python3 scripts/changelog.py add");
    expect(result).toContain("python3 scripts/changelog.py list");
    expect(result).toContain("python3 scripts/changelog.py search");
  });
});
