import { describe, it, expect } from "vitest";
import { generateClaudeMd } from "./claude_md.js";
import type { RuleDecision } from "../types.js";

function cognitiveRule(overrides?: Partial<RuleDecision>): RuleDecision {
  return {
    ruleId: "R003",
    ruleName: "prefer-early-return",
    recommendedMedium: "claude_md",
    alternativeMedia: [],
    confidence: 0.7,
    reasons: ["Use early returns to reduce nesting"],
    cognitiveLayerRequired: true,
    cognitiveSkillTriggers: ["diagnostic", "educational"],
    ...overrides,
  };
}

function softRule(overrides?: Partial<RuleDecision>): RuleDecision {
  return {
    ruleId: "R013",
    ruleName: "code-review-required",
    recommendedMedium: "claude_md",
    alternativeMedia: [],
    confidence: 0.8,
    reasons: ["All important changes must be reviewed"],
    cognitiveLayerRequired: false,
    cognitiveSkillTriggers: [],
    ...overrides,
  };
}

function refRule(overrides?: Partial<RuleDecision>): RuleDecision {
  return {
    ruleId: "R001",
    ruleName: "no-console-log",
    recommendedMedium: "linter_warn",
    alternativeMedia: [],
    confidence: 0.85,
    reasons: ["Use logger instead"],
    cognitiveLayerRequired: false,
    cognitiveSkillTriggers: [],
    ...overrides,
  };
}

describe("generateClaudeMd", () => {
  // 1. 空 decisions
  it("produces output with no rule blocks for empty decisions", () => {
    const result = generateClaudeMd({ decisions: [] });
    expect(result.length).toBeGreaterThan(0);
    expect(result).not.toContain("###");
    // Prose mentions are OK; actual rule section headers should not appear
    expect(result).not.toContain("## 认知层规则");
    expect(result).not.toContain("## 软约束规则");
    expect(result).not.toContain("## 参考规则");
    // Harness overview section is always present
    expect(result).toContain("## Harness 约束体系");
  });

  // 2. 仅 cognitive rules
  it("includes cognitive section for cognitive-only decisions", () => {
    const result = generateClaudeMd({ decisions: [cognitiveRule()] });
    expect(result).toContain("## 认知层规则 (Cognitive Rules)");
    expect(result).toContain("prefer-early-return");
    expect(result).toContain("diagnostic");
    expect(result).toContain("educational");
  });

  // 3. 仅指引规则
  it("includes guidelines section for claude_md non-cognitive decisions", () => {
    const decisions = [
      softRule(),
      softRule({ ruleId: "R009", ruleName: "no-duplicate-code", reasons: ["Extract common logic"] }),
    ];
    const result = generateClaudeMd({ decisions });
    expect(result).toContain("## 指引规则 (Guidelines)");
    expect(result).toContain("code-review-required");
    expect(result).toContain("no-duplicate-code");
  });

  // 4. 混合类型
  it("includes all sections for mixed decision types", () => {
    // refRule with "hook" medium → goes to reference section
    const ref = refRule({ recommendedMedium: "hook" });
    const decisions = [cognitiveRule(), softRule(), ref];
    const result = generateClaudeMd({ decisions });
    expect(result).toContain("认知层规则");
    expect(result).toContain("指引规则 (Guidelines)");
    expect(result).toContain("参考规则 (Reference)");
    expect(result).toContain("→ 由 `hook` 自动执行");
  });

  // 5. projectName 参数
  it("uses projectName in the title", () => {
    const result = generateClaudeMd({ decisions: [], projectName: "MyApp" });
    expect(result.startsWith("# MyApp — Harness Rules")).toBe(true);
  });

  // 内容结构断言
  it("includes auto-generated mark and version footer", () => {
    const result = generateClaudeMd({ decisions: [cognitiveRule()] });
    expect(result).toContain("Auto-generated by Harness Automation System");
    expect(result).toContain("Generated by Harness Automation System v1.0");
  });
});
