import type { RuleDecision } from "../types.js";

export interface ClaudeMdConfig {
  decisions: RuleDecision[];
  projectName?: string;
  collaborationMode?: "solo" | "team";
  gitProvider?: "github" | "gitlab" | "both";
}

/**
 * Generate CLAUDE.md content from rule decisions.
 * CLAUDE.md is the "soft constraint" medium — loaded every session.
 */
export function generateClaudeMd(config: ClaudeMdConfig): string {
  const { decisions, projectName } = config;

  const lines: string[] = [];
  lines.push(`# ${projectName || "Project"} — Harness Rules`);
  lines.push("");
  lines.push("<!-- Auto-generated by Harness Automation System -->");
  lines.push("");
  lines.push("## Harness 约束体系");
  lines.push("");
  lines.push("本文档由 Harness Automation System 自动生成和维护，列出项目应遵守的开发约束。");
  lines.push("约束按强度分为硬约束（必须遵守）、认知层规则（需主动判断）、软约束（linter 提醒）和参考规则（自动执行）。");
  lines.push("");

  // Hard constraints section (R017 task-board, R018 changelog-convention)
  const hardConstraintIds = new Set(["R017", "R018"]);
  const hardConstraints = decisions.filter((d) => hardConstraintIds.has(d.ruleId));

  if (hardConstraints.length > 0) {
    lines.push("## 硬约束 (Hard Constraints)");
    lines.push("");
    lines.push("以下规则是项目级别的刚性约束，必须严格遵守：");
    lines.push("");

    for (const rule of hardConstraints) {
      if (rule.ruleName === "task-board") {
        lines.push("### 任务看板管理");
        lines.push("");
        lines.push("- **规则**: 只能使用 `scripts/task.py` 脚本操作 `TASK.json` 任务看板");
        lines.push("- **禁止**: 直接手动编辑 `TASK.json` 文件");
        lines.push("- **用法**:");
        lines.push("  ```bash");
        lines.push("  python3 scripts/task.py list [--status pending|completed|in_progress] [--phase <n>] [--priority high|medium|low|critical]");
        lines.push("  python3 scripts/task.py show <id>");
        lines.push("  python3 scripts/task.py update <id> <status>");
        lines.push("  python3 scripts/task.py summary");
        lines.push("  ```");
        lines.push("");
      }
      if (rule.ruleName === "changelog-convention") {
        lines.push("### 变更日志管理");
        lines.push("");
        lines.push("- **规则**: 只能使用 `scripts/changelog.py` 脚本操作 `CHANGELOG.jsonl` 变更日志");
        lines.push("- **禁止**: 直接手动编辑 `CHANGELOG.jsonl` 文件");
        lines.push("- **用法**:");
        lines.push("  ```bash");
        lines.push("  python3 scripts/changelog.py add <type> <phase> <description>");
        lines.push("  python3 scripts/changelog.py list [n]");
        lines.push("  python3 scripts/changelog.py search <keyword>");
        lines.push("  ```");
        lines.push("");
      }
    }
  }

  // Design §8.1: CLAUDE.md includes claude_md and linter_warn rules only.
  // claude_md: cognitive guidance (both formal and non-formalizable rules that need LLM awareness)
  // linter_warn: soft constraints (should explain when it's OK to ignore)
  const claudeMdRules = decisions.filter(
    (d) => (d.recommendedMedium === "claude_md" || d.recommendedMedium === "claude.md") && !hardConstraintIds.has(d.ruleId),
  );
  const softRules = decisions.filter(
    (d) => d.recommendedMedium === "linter_warn" || d.recommendedMedium === "linter",
  );
  const inClaudeMd = new Set([
    ...claudeMdRules.map((d) => d.ruleId),
    ...softRules.map((d) => d.ruleId),
  ]);
  const referenceRules = decisions.filter(
    (d) => !inClaudeMd.has(d.ruleId),
  );

  // Cognitive subsection (rules needing cognitive support inside claude_md)
  const cognitiveRules = claudeMdRules.filter((d) => d.cognitiveLayerRequired);
  const guidelineRules = claudeMdRules.filter((d) => !d.cognitiveLayerRequired);

  if (cognitiveRules.length > 0) {
    lines.push("## 认知层规则 (Cognitive Rules)");
    lines.push("");
    lines.push("以下规则需要您在开发过程中主动判断和遵守：");
    lines.push("");
    for (const rule of cognitiveRules) {
      lines.push(`### ${rule.ruleName}`);
      lines.push(`- **规则**: ${rule.reasons[0] || ""}`);
      for (const trigger of rule.cognitiveSkillTriggers) {
        lines.push(`- **认知层辅助**: 触发 "${trigger}" Skill`);
      }
      lines.push("");
    }
  }

  if (guidelineRules.length > 0) {
    lines.push("## 指引规则 (Guidelines)");
    lines.push("");
    lines.push("以下规则为开发指引，建议在开发过程中参考：");
    lines.push("");
    for (const rule of guidelineRules) {
      lines.push(`- **${rule.ruleName}**: ${rule.reasons.join("; ")}`);
    }
    lines.push("");
  }

  if (softRules.length > 0) {
    lines.push("## 软约束规则 (Soft Constraints)");
    lines.push("");
    lines.push("以下规则通过 linter 警告提醒，您在理解背景后可酌情跳过：");
    lines.push("");
    for (const rule of softRules) {
      lines.push(`- **${rule.ruleName}**: ${rule.reasons.join("; ")}`);
    }
    lines.push("");
  }

  if (referenceRules.length > 0) {
    lines.push("## 参考规则 (Reference)");
    lines.push("");
    lines.push("以下规则已通过其他介质自动执行：");
    lines.push("");
    for (const rule of referenceRules) {
      lines.push(
        `- **${rule.ruleName}** → 由 \`${rule.recommendedMedium}\` 自动执行`,
      );
    }
    lines.push("");
  }

  // Team Collaboration section — only when collaborationMode is "team"
  if (config.collaborationMode === "team") {
    lines.push("## Team Collaboration");
    lines.push("");

    lines.push("### Git 工作流");
    lines.push("- 分支命名：feature/<描述>, bugfix/<描述>, hotfix/<描述>, release/<版本>");
    lines.push("- 从 main 分支创建功能分支，完成后通过 Merge Request 合并");
    if (config.gitProvider === "both") {
      lines.push("- 双远程：GitLab（团队主仓库）+ GitHub（个人备份）");
    }
    lines.push("");

    lines.push("### Code Review");
    lines.push("- 所有 MR 需要至少 1 人 Approve");
    lines.push("- AI Code Review 在 CI 中自动运行，审查结果作为参考");
    lines.push("- Review 关注：逻辑正确性、安全性、性能、可维护性");
    lines.push("");

    lines.push("### AI 参与度记录");
    lines.push("- 在 MR 描述中标注 AI 工具使用情况");
    lines.push("- 提交信息中使用 Co-Authored-By 标注 AI 参与");
    lines.push("");

    lines.push("### 新成员 Onboarding");
    lines.push("- 运行 `bash scripts/onboard.sh` 完成环境配置");
    lines.push("- 阅读 `.gitlab/merge_request_templates/default.md` 了解 MR 规范");
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by Harness Automation System v1.0*");

  return lines.join("\n");
}
