import type { RuleDecision } from "../types.js";

export interface GitlabSettingsConfig {
  decisions: RuleDecision[];
  projectUrl?: string;
  projectId?: string;
}

export interface GitlabSettingsOutput {
  script: { path: string; content: string; executable: boolean };
  doc: { path: string; content: string };
}

function generateScript(decisions: RuleDecision[], projectUrl?: string, projectId?: string): { path: string; content: string; executable: boolean } {
  const lines: string[] = [];

  lines.push("#!/bin/bash");
  lines.push("");
  lines.push("set -euo pipefail");
  lines.push("");
  lines.push("# ============================================================");
  lines.push("# GitLab Settings Configuration Script");
  lines.push("# Generated by Harness Automation");
  lines.push("# ============================================================");
  lines.push("#");
  lines.push("# This script contains curl commands to configure GitLab project");
  lines.push("# settings via the GitLab API. Each command is commented out so");
  lines.push("# you can review and run them individually.");
  lines.push("#");
  lines.push("# Usage:");
  lines.push("#   1. Set GITLAB_TOKEN environment variable");
  lines.push("#   2. Uncomment the commands you want to apply");
  lines.push("#   3. Run: bash scripts/gitlab-configure.sh");
  lines.push("#");
  lines.push("");

  const projectRef = projectId ? `projects/${projectId}` : "projects/:PROJECT_ID";
  const baseUrl = projectUrl
    ? projectUrl.replace(/\/$/, "")
    : "https://gitlab.example.com";

  // Check for token
  lines.push("# Verify GitLab token is set");
  lines.push('# if [ -z "${GITLAB_TOKEN:-}" ]; then');
  lines.push('#   echo "Error: GITLAB_TOKEN environment variable is not set"');
  lines.push("#   exit 1");
  lines.push("# fi");
  lines.push("");

  // Protected branches
  lines.push("# ----------------------------------------------------------");
  lines.push("# Protected Branches (main/master)");
  lines.push("# Prevents direct pushes/force-pushes to protected branches.");
  lines.push("# ----------------------------------------------------------");
  lines.push("");
  lines.push("# # Protect the main branch");
  lines.push(`# curl --request POST \\`);
  lines.push(`#   --header "PRIVATE-TOKEN: \${GITLAB_TOKEN}" \\`);
  lines.push(`#   "${baseUrl}/api/v4/${projectRef}/protected_branches" \\`);
  lines.push(`#   --data "name=main&push_access_level=0&merge_access_level=30"`);
  lines.push("");
  lines.push("# # Protect the master branch (if using master instead of main)");
  lines.push(`# curl --request POST \\`);
  lines.push(`#   --header "PRIVATE-TOKEN: \${GITLAB_TOKEN}" \\`);
  lines.push(`#   "${baseUrl}/api/v4/${projectRef}/protected_branches" \\`);
  lines.push(`#   --data "name=master&push_access_level=0&merge_access_level=30"`);
  lines.push("");

  // Push rules
  lines.push("# ----------------------------------------------------------");
  lines.push("# Push Rules");
  lines.push("# Enforces commit message format, branch naming, and file size limits.");
  lines.push("# ----------------------------------------------------------");
  lines.push("");
  lines.push("# # Configure push rules for the project");
  lines.push(`# curl --request POST \\`);
  lines.push(`#   --header "PRIVATE-TOKEN: \${GITLAB_TOKEN}" \\`);
  lines.push(`#   "${baseUrl}/api/v4/${projectRef}/push_rule" \\`);
  lines.push(`#   --data "commit_message_regex=^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)\\(.+\\): .+" \\`);
  lines.push(`#   --data "branch_name_regex=^(main|master|develop|feature/.+|bugfix/.+|hotfix/.+|release/.+)$" \\`);
  lines.push(`#   --data "max_file_size=5" \\`);
  lines.push(`#   --data "prevent_secrets=true"`);
  lines.push("");

  // Merge request approvals
  lines.push("# ----------------------------------------------------------");
  lines.push("# Merge Request Approvals");
  lines.push("# Requires at least 1 approver before merging.");
  lines.push("# ----------------------------------------------------------");
  lines.push("");
  lines.push("# # Set minimum required approvers to 1");
  lines.push(`# curl --request PUT \\`);
  lines.push(`#   --header "PRIVATE-TOKEN: \${GITLAB_TOKEN}" \\`);
  lines.push(`#   "${baseUrl}/api/v4/${projectRef}/approvals" \\`);
  lines.push(`#   --data "approvals_before_merge=1"`);
  lines.push("");

  // Security features
  lines.push("# ----------------------------------------------------------");
  lines.push("# Security Features");
  lines.push("# Enables SAST, secret detection, dependency scanning, and container scanning.");
  lines.push("# ----------------------------------------------------------");
  lines.push("");
  lines.push("# # Enable security features via project settings");
  lines.push(`# curl --request PUT \\`);
  lines.push(`#   --header "PRIVATE-TOKEN: \${GITLAB_TOKEN}" \\`);
  lines.push(`#   "${baseUrl}/api/v4/${projectRef}" \\`);
  lines.push(`#   --data "jobs_enabled=true" \\`);
  lines.push(`#   --data "container_registry_enabled=true" \\`);
  lines.push(`#   --data "security_and_compliance_enabled=true"`);
  lines.push("");

  lines.push("echo \"GitLab configuration script review complete.\"");
  lines.push("echo \"Uncomment the commands above and re-run to apply settings.\"");

  const content = lines.join("\n");
  return {
    path: "scripts/gitlab-configure.sh",
    content,
    executable: true,
  };
}

function generateDoc(decisions: RuleDecision[]): { path: string; content: string } {
  const lines: string[] = [];

  lines.push("# GitLab Settings");
  lines.push("");
  lines.push("This document describes the recommended GitLab project settings for team collaboration.");
  lines.push("Below you will find explanations of each setting, how to configure them via the GitLab Web UI,");
  lines.push("and the recommended values for a productive team workflow.");
  lines.push("");

  // Protected Branches
  lines.push("## Protected Branches");
  lines.push("");
  lines.push("**What it does:** Prevents direct pushes and force-pushes to important branches (e.g., `main`, `master`).");
  lines.push("All changes must go through merge requests with proper review.");
  lines.push("");
  lines.push("**Recommended Values:**");
  lines.push("- **Allowed to push:** No one (0 — maintainers only via MR)");
  lines.push("- **Allowed to merge:** Maintainers (30)");
  lines.push("- **Protected branches:** `main`, `master`");
  lines.push("");
  lines.push("**Configure via Web UI:**");
  lines.push("1. Go to **Settings > Repository > Protected Branches**");
  lines.push("2. Select the branch from the dropdown");
  lines.push("3. Set allowed to merge and allowed to push");
  lines.push("4. Click **Protect**");
  lines.push("");

  // Push Rules
  lines.push("## Push Rules");
  lines.push("");
  lines.push("**What it does:** Enforces rules on git pushes — commit message format, branch naming conventions,");
  lines.push("maximum file size, and secret detection.");
  lines.push("");
  lines.push("**Recommended Values:**");
  lines.push("- **Commit message regex:** `^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(...): .+` (Conventional Commits)");
  lines.push("- **Branch name regex:** `^(main|master|develop|feature/.+|bugfix/.+|hotfix/.+|release/.+)$`");
  lines.push("- **Max file size:** 5 MB");
  lines.push("- **Prevent secrets:** Enabled");
  lines.push("");
  lines.push("**Configure via Web UI:**");
  lines.push("1. Go to **Settings > Repository > Push Rules**");
  lines.push("2. Fill in the desired rules");
  lines.push("3. Click **Save Push Rules**");
  lines.push("> **Note:** Push rules require GitLab Premium or Ultimate.");
  lines.push("");

  // Merge Request Approvals
  lines.push("## Merge Request Approvals");
  lines.push("");
  lines.push("**What it does:** Requires a minimum number of approvals before a merge request can be merged.");
  lines.push("This ensures that at least one other team member reviews every change.");
  lines.push("");
  lines.push("**Recommended Values:**");
  lines.push("- **Approvals required:** 1 (minimum for team collaboration)");
  lines.push("- **Approvers:** Maintainers or designated reviewers");
  lines.push("");
  lines.push("**Configure via Web UI:**");
  lines.push("1. Go to **Settings > Merge Requests > Approvals**");
  lines.push("2. Set the number of required approvals");
  lines.push("3. Optionally add specific approvers");
  lines.push("4. Click **Save changes**");
  lines.push("");

  // Security Features
  lines.push("## Security Features");
  lines.push("");
  lines.push("**What it does:** Enables built-in security scanning tools including SAST (Static Application Security Testing),");
  lines.push("secret detection, dependency scanning, and container scanning.");
  lines.push("");
  lines.push("**Recommended Values:**");
  lines.push("- **SAST:** Enabled (runs on every pipeline)");
  lines.push("- **Secret Detection:** Enabled");
  lines.push("- **Dependency Scanning:** Enabled");
  lines.push("- **Container Scanning:** Enabled");
  lines.push("- **Security & Compliance:** Enabled");
  lines.push("");
  lines.push("**Configure via Web UI:**");
  lines.push("1. Go to **Settings > Security & Compliance > Configuration**");
  lines.push("2. Enable the desired security features");
  lines.push("3. These can also be configured via `.gitlab-ci.yml` for finer control");
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push("");
  lines.push("| Setting | Recommended | Location |");
  lines.push("|---|---|---|");
  lines.push("| Protected Branches | main, master | Settings > Repository |");
  lines.push("| Push Rules | Conventional Commits, branch naming, max file size 5MB | Settings > Repository |");
  lines.push("| MR Approvals | 1 approval required | Settings > Merge Requests |");
  lines.push("| Security Features | SAST, Secret Detection, Dependency Scanning | Settings > Security & Compliance |");
  lines.push("");
  lines.push("For automated configuration, review and run the companion script: `scripts/gitlab-configure.sh`.");

  const content = lines.join("\n");
  return {
    path: "docs/gitlab-settings.md",
    content,
  };
}

/**
 * Generate GitLab settings configuration — a bash script with commented curl commands
 * and a markdown documentation file. Always produces both outputs regardless of decisions.
 */
export function generateGitlabSettings(config: GitlabSettingsConfig): GitlabSettingsOutput {
  const script = generateScript(config.decisions, config.projectUrl, config.projectId);
  const doc = generateDoc(config.decisions);

  return { script, doc };
}
